# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad4753c006731737a935f481f12e9f65d819867ee8137e1e1765a5edc16eba51d35bab81959e42e30baae5da619c146a275da4d1c20a36ebe7d78d08b05f53fb
  GITHUB_KEY: 3bd2f99d600d2fabd6f2
  GITHUB_SECRET: 6fbaac5201a20e7ac34ab4bc62e93d7d2cfc7918

test:
  secret_key_base: b3ed2ce7c0ce6774469a20dfefa9c6566ffde8eb9b522c8ac0954db7491791163041471caa3938661678fa08ac721c33b4e2a27773df8a9e11078a516f35259e
  GITHUB_KEY: 3bd2f99d600d2fabd6f2
  GITHUB_SECRET: 6fbaac5201a20e7ac34ab4bc62e93d7d2cfc7918
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  GITHUB_KEY: d8adc7a3be252d366cbf
  GITHUB_SECRET: 6152ca7a9ccca37956e6e980a1eb60053f4ac53a
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
